language: node_js
install: npm install
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Discovery-API to AWS.'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: discovery-api
  env: discovery-api-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-api-production
  on:
    repo: NYPL/discovery-api
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: discovery-api
  env: discovery-api-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-api-qa
  on:
    repo: NYPL/discovery-api
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: discovery-api
  env: discovery-api-dev
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: discovery-api-dev
  on:
    repo: NYPL/discovery-api
    branch: development
after_deploy: echo 'Successfully executed deploy trigger for Discovery API'
notifications:
  slack:
    secure: g6eiX6ALpd0VvGsSCDyCGpwtkvTT3qDcNTwXFK7yj85y4ZaRPUHqV22RXUn+7hyvPDbaXM1o61Q5EwBCC3XGlzirqGoM0l22TDQq3ZchtJGTSFrALcWGHaj6YHCQOyHu4TbFsaYGzMNG0o2DVjC2A1L/psoLVj5S0mQXtRmsWNiBAfff4kqOBYk76459rCkAGoUkV5Wwz6D0XPdLxVFmOqtfFdt427jjZcQp9tj5as9B33ERm4kdIKX2/CXdJE3F7+YjKeyrUhrqggLRJiTBKc53reoy8X26QjExfQ95ewPkdHx+CAnXKhW1TLym4+EpRTSrQIFt2dhKvT+0VU4X3XIKlxTn2KA/UX/1Qln6s8SMRqzeaNqB6t8rckzqQ3NN5HSgHmcERnmwFaRM4mPfxwTf5RR0bnoZd4iq7x3hiznztLJp3S5i1hUQCm8IJ83sTEU9LHsVdaaBjTOk7FAtATGX3IGA86BKVvdpULgQFaucAx5jRXIGyRFqcuzka3B4UYSyfatU3i+KRVDIuo+PkbcsjLL7EGT3fPZVeXgXnxdLQT7s9mKtEMhCDGOzH4gApJJn62Z+x0m3hoUgR8Y5sw9o9yoiwD2ldlQtYQ/1iMP/mku3gyF8nsCe9AR3nMmUJGyCufEBOTR8A6THscINRU/4pVxWfdFDAUjz1qoADKM=
env:
  global:
    secure: tg3Snnk8PJdV4qMkP4QY9Fg030NyGjsYywVHfSEgO+azNsgv/yMKMUZEbtvWiGYSSN5gP58cIenDqbEPn7Kv/7iVkisb8nqA/Gw+w+MSYitgbUUuL4hubyEBdtJiEi2ifpcyMUF5lHSc8qixnX0mzGzVdF9h91UV7oWM9vPaPHPErlLPuaPO58WfZ6F6UqjIN1a4pigzPf9fvrSm/ziS3NHuJUoH8Mjo1J60tJ+hjlo5s2l1N9RjObKo9wAaMXcFv9gHMMoO98rflIPITlYdpziCsjiJ+vp8Yq0Tx5es99LLxqMd5D53w9GRx11Bfa3uTlp/Y4B2xQPZ0D9MNVttG+rvtY5/cyPWT4DvyM1MXfzF0bag8aLlYfctNYL03gUsfC/G/uEb0i8oz8SSqu79NOAV2yU/ZNoupivtlDaYBmeARshOA6MaFdD2Bh2MAq59R+5jDu4A0lyq3HBxmum8Qi5uBsNHQXLKaJlyk1/Ay89LTuDtS1DrrsfGfckAdIDKZ0Qo08yXOEspHVbba0jTaX4CL6vn7L30avZxnze53DI8239+0uqpjK6KyuQOblND0xYywqpH57Ev5VPXeQ0lWzbPx8/W+C3fdLZLNU0a1HVaCL12qoQkp0rtdPj4CjIObjBw9Sx+W/ND9u1+rQZqcaL5MkUVJctvHbxFjP7nf4A=
