language: node_js
install: npm install
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Discovery-API to AWS.'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: discovery-api
  env: discovery-api-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-api-production
  on:
    repo: NYPL/discovery-api
    branch: production
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: discovery-api
  env: discovery-api-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: discovery-api-qa
  on:
    repo: NYPL/discovery-api
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: discovery-api
  env: discovery-api-dev
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: discovery-api-dev
  on:
    repo: NYPL/discovery-api
    branch: development
after_deploy: echo 'Successfully executed deploy trigger for Discovery API'
notifications:
  slack:
    secure: g6eiX6ALpd0VvGsSCDyCGpwtkvTT3qDcNTwXFK7yj85y4ZaRPUHqV22RXUn+7hyvPDbaXM1o61Q5EwBCC3XGlzirqGoM0l22TDQq3ZchtJGTSFrALcWGHaj6YHCQOyHu4TbFsaYGzMNG0o2DVjC2A1L/psoLVj5S0mQXtRmsWNiBAfff4kqOBYk76459rCkAGoUkV5Wwz6D0XPdLxVFmOqtfFdt427jjZcQp9tj5as9B33ERm4kdIKX2/CXdJE3F7+YjKeyrUhrqggLRJiTBKc53reoy8X26QjExfQ95ewPkdHx+CAnXKhW1TLym4+EpRTSrQIFt2dhKvT+0VU4X3XIKlxTn2KA/UX/1Qln6s8SMRqzeaNqB6t8rckzqQ3NN5HSgHmcERnmwFaRM4mPfxwTf5RR0bnoZd4iq7x3hiznztLJp3S5i1hUQCm8IJ83sTEU9LHsVdaaBjTOk7FAtATGX3IGA86BKVvdpULgQFaucAx5jRXIGyRFqcuzka3B4UYSyfatU3i+KRVDIuo+PkbcsjLL7EGT3fPZVeXgXnxdLQT7s9mKtEMhCDGOzH4gApJJn62Z+x0m3hoUgR8Y5sw9o9yoiwD2ldlQtYQ/1iMP/mku3gyF8nsCe9AR3nMmUJGyCufEBOTR8A6THscINRU/4pVxWfdFDAUjz1qoADKM=
env:
  global:
    secure: F96pXMAonEzAc8ju+HrZmtKDid7RO2D+xNyiRI50XmL4ileGQDpvNxleaxW/l81KU7DfFpUoUSsGbbtFfpBavRfa2vdW01tONj7neUVmzGmCHzyT8oHxOrc+SdfsuWbjdQ7V+rZbA7qGt5H0NL40gKJUK1dqM936LzFw1y4nXTEz5Pf7MYby3UqyqCj3wFW4MVCaSFHz/v6DMdNCztkeEfHAnTJxEzwIc7oz3rUs7fngVX4U1LSb5ZeTRfVM/6G/kgUH0+Z2FbGw7vKbQXnH0Old9E/GxOXOrdpsBfpTDT/Q0+xCwA9geAVu2dVS+NcoaqSbVdvz7Sk7DJcGAVRhX78OiCHMK1QGWIwO4QOEzenr1Y1JExrKUzhkeN/7XoTv3WQ0RC+dwBa1hf7r/NSa3DSWqGXPeQxMeBoQ+m0tJKIEat7e/jD/y+vvUJRNZ5iN+rk14gbTB2uwQza3fHUYXw5Ep0m2MLCrLODWQyIuHAaHVEnT1o8GXeY2kAmrMSXbBIn/utJmzk+4eoduZyouR8Pc8vBLYCsUELtmsMOdDiV4SjYcdnJzSLIZibm35FZzCo0JyE6zzUCaKBGNkKe/PiQTMbPCi2AMi9OIw9x152N51E6GHZ/h75YDsHkh+k88IWv+u1MLUsvg6WLH2Tksc+F8qGZVFy8wEBBzudv9DKM=
