version: '3'
services:
  app:
    build:
      context: .
    volumes:
    - ./:/app
    ports:
    - '8082:8082'
    environment:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
