on:
  pull_request:
    branches:
      - qa

jobs:
  integration-test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm i
      - name: Run integration tests
        env: 
          ENV: 'qa'
        run: node test/integration/delivery-locations-by-barcode.test.js
