on: [workflow_call]

jobs:
  integration-test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: node test/integration/delivery-locations-by-barcode.test.js
