on:
  pull_request:
    branches:
      - production

jobs:
  integration-test:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        env: 
          ENV: 'qa'
        run: node test/integration/delivery-locations-by-barcode.test.js
