name: Unit Tests

on: 
  workflow_call:
  push:

permissions:
  contents: read

jobs:
  changelog:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/production')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Enforce CHANGELOG update
        uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: 'skip-changelog'
  tests:
    permissions:
        id-token: write
        contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm ci
      - name: Unit Tests
        run: npm test